[env]

TERM = "xterm-256color"

[window]

padding.x = 5
padding.y = 5

decorations = "Full"

opacity = 1
blur = true

option_as_alt = "Both"

[scrolling]

history = 10000
multiplier = 3

[font]

normal.family = "Monaspace Xenon"
bold.family = "Monaspace Xenon"
italic.family = "Monaspace Xenon"
bold_italic.family = "Monaspace Xenon"

size = 14
